wait for postgresql server to initialize database for LocalDS

diff --git a/src/jboss-eap.init b/src/jboss-eap.init
--- a/src/jboss-eap.init
+++ b/src/jboss-eap.init
@@ -25,10 +25,6 @@
 # Check that networking is up.
 [ ${NETWORKING} = "no" ] && exit 0
 
-if [ -f /usr/share/jboss-eap-local-ds/jboss-eap-local-ds-preconfigure.sh ]; then
-    /usr/share/jboss-eap-local-ds/jboss-eap-local-ds-preconfigure.sh
-fi
-
 NAME="jboss-eap"
 
 unset ISBOOT
@@ -218,6 +214,28 @@ function procrunning() {
 }
 
 start() {
+    if [ -f /usr/share/jboss-eap-local-ds/jboss-eap-local-ds-preconfigure.sh ]; then
+        sleep=0
+        RETVAL=1
+        while [ $sleep -lt 60 -a $RETVAL -eq 1 ]; do
+            sleep 2
+            sleep=`expr $sleep + 5`
+
+            service postgresql status > /dev/null
+
+            if [ $? -eq 0 ]; then
+                sleep 5
+                /usr/share/jboss-eap-local-ds/jboss-eap-local-ds-preconfigure.sh > /dev/null
+                RETVAL=0
+            fi
+        done
+
+        if [ $RETVAL -eq 1 ]; then
+            echo "Error while waiting for PostgreSQL server..."
+            exit
+        fi
+    fi
+
     echo -n "Starting ${NAME}: "
 
     # if lock file exists
